language: en
save_directory: ~/Library/Application Support/Anki2/User 1/collection.media
# Anki indexes files only at the collection.media root.
media_subdirectory: ""
input_file: ../vocab_exploration/en/data/new_words_enriched.json
output_file: ../vocab_exploration/en/data/new_words_enriched_with_audio.json
