# Flashcard Converter Configuration

# Path to the input JSON file with meta information
input_file: "data/meta.json"

# Name of the Anki deck to create/populate
deck_name: "My Flashcard Deck"

# Flashcard Templates
# Each template includes:
# - front: Template string for the front of the flashcard
# - back: Template string for the back of the flashcard
flashcard_template:
  - front: |-
      {word} <br>
      {example}
    back: |-
      {definition} <br> <br>
      [sound:{audio}]
  
  # You can add more templates for different types of flashcards
  # - front: "{word}"
  #   back: "{definition}"