api:
  model: "gpt-3.5-turbo"
prompt_path: "prompt.md"
handler:
  retries: 3
  sleep_time: 2
  timeout: 30
  max_tokens: 1000
  temperature: 0.7
validators:
  json:
    require_schema: false
    schema_path: ""