api:
  type: "nebius"
  model: "deepseek-ai/DeepSeek-V3-0324"
  base_url: "https://api.studio.nebius.ai/v1"
  params:
    temperature: 0.7
    max_tokens: 1000  # Increased from 100 to 1000 to allow for complete responses
    timeout: 30       # Request timeout in seconds for Nebius API
prompt_path: "prompt.md"
# Default input and output paths (optional)
input: "example_input.json"
output: "example_output.json" 