"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {
    'packages': ['PyQt5', 'pynput'],
    'plist': {
        # 'CFBundleShortVersionString': '1.0.0',
        'LSBackgroundOnly': True,  # Makes it a background app
        'LSUIElement': True,       # Hides it from Dock
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
